Write a function so that the columns of the output matrix are powers of the input vector. 
The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [77]:
import numpy as np

In [98]:
def Vandermonde(li, increasing):
    n = int(len(li))
    x = np.zeros((n,n),dtype = int)
    if increasing:
        for i in range(0,len(li)):
            t = list(map(lambda x : x**i, li))
            x[i] = t
    else:
        for i in range(0,len(li)):
            t = list(map(lambda x : x**(n-i-1), li))
            x[i] = t


    return(x.transpose())
            
        

In [99]:
li = [2,3,4,5]
Vandermonde(li,True)

array([[  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   4,  16,  64],
       [  1,   5,  25, 125]])

In [100]:
li = [2,3,4,5]
Vandermonde(li,False)

array([[  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [101]:
np.vander(li)

array([[  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

Write a function to find moving average in an array over a window: 

In [103]:
lm = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [111]:
def moving_average(lm, k):
    res = list()
    n = len(lm)
    k=3
    for i in range(0,n-k+1):
        res.append(round(np.sum(lm[i:i+k])/k,2))
    return(res)

moving_average(lm,3)


[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

In [117]:
def moving_average(lm, k):
    return(np.convolve(lm,np.ones(k),'valid')/k)

lm = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
moving_average(lm,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])